type Query {
    assigneds(request: AssignRequest): [UserJobAssigned]
    userById(id:ID): User
}
type Mutation {
    addJob(request: JobRequest): Job
}

type UserJobAssigned {
    users: [User]
    job: Job
}

type User {
    id: ID
    firstName: String
    lastName: String
    email:String
    job:Job

}

type Job {
    name:String
    salary:Float
    hours:Float
    id:ID
    resources:Float
}

input AssignRequest {
    requestNumber: Int
    clientName: String
}

input JobRequest {
    name: String
    salary: Float
    hours: Float
    resources: Float
}